export const COUNTRIES = [
  { value: "PK", label: "Pakistan" },
  { value: "US", label: "United States" },
  { value: "GB", label: "United Kingdom" },
  { value: "CA", label: "Canada" },
  { value: "AU", label: "Australia" },
  { value: "AE", label: "United Arab Emirates" },
  { value: "SA", label: "Saudi Arabia" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "IN", label: "India" },
];

export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];

export const US_CITIES_BY_STATE: Record<
  string,
  { value: string; label: string }[]
> = {
  NY: [
    { value: "NYC", label: "New York City" },
    { value: "BUF", label: "Buffalo" },
    { value: "ROC", label: "Rochester" },
    { value: "SYR", label: "Syracuse" },
    { value: "ALB", label: "Albany" },
  ],
  TX: [
    { value: "HOU", label: "Houston" },
    { value: "SA", label: "San Antonio" },
    { value: "DAL", label: "Dallas" },
    { value: "AUS", label: "Austin" },
    { value: "FW", label: "Fort Worth" },
  ],
  AL: [
    { value: "Birmingham", label: "Birmingham" },
    { value: "Montgomery", label: "Montgomery" },
    { value: "Huntsville", label: "Huntsville" },
    { value: "Mobile", label: "Mobile" },
    { value: "Tuscaloosa", label: "Tuscaloosa" },
    { value: "Hoover", label: "Hoover" },
    { value: "Dothan", label: "Dothan" },
    { value: "Auburn", label: "Auburn" },
    { value: "Decatur", label: "Decatur" },
    { value: "Madison", label: "Madison" },
    { value: "Florence", label: "Florence" },
    { value: "Gadsden", label: "Gadsden" },
    { value: "Vestavia Hills", label: "Vestavia Hills" },
    { value: "Prattville", label: "Prattville" },
    { value: "Phenix City", label: "Phenix City" },
    { value: "Alabaster", label: "Alabaster" },
    { value: "Bessemer", label: "Bessemer" },
    { value: "Enterprise", label: "Enterprise" },
    { value: "Opelika", label: "Opelika" },
    { value: "Homewood", label: "Homewood" },
    { value: "Northport", label: "Northport" },
    { value: "Anniston", label: "Anniston" },
    { value: "Prichard", label: "Prichard" },
    { value: "Athens", label: "Athens" },
    { value: "Daphne", label: "Daphne" },
    { value: "Talladega", label: "Talladega" },
    { value: "Selma", label: "Selma" },
    { value: "Oxford", label: "Oxford" },
    { value: "Mountain Brook", label: "Mountain Brook" },
    { value: "Trussville", label: "Trussville" },
  ],
  CA: [
    { value: "Los Angeles", label: "Los Angeles" },
    { value: "San Diego", label: "San Diego" },
    { value: "San Jose", label: "San Jose" },
    { value: "San Francisco", label: "San Francisco" },
    { value: "Fresno", label: "Fresno" },
    { value: "Sacramento", label: "Sacramento" },
    { value: "Long Beach", label: "Long Beach" },
    { value: "Oakland", label: "Oakland" },
    { value: "Bakersfield", label: "Bakersfield" },
    { value: "Anaheim", label: "Anaheim" },
    { value: "Santa Ana", label: "Santa Ana" },
    { value: "Riverside", label: "Riverside" },
    { value: "Stockton", label: "Stockton" },
    { value: "Irvine", label: "Irvine" },
    { value: "Chula Vista", label: "Chula Vista" },
    { value: "Fremont", label: "Fremont" },
    { value: "San Bernardino", label: "San Bernardino" },
    { value: "Modesto", label: "Modesto" },
    { value: "Fontana", label: "Fontana" },
    { value: "Oxnard", label: "Oxnard" },
    { value: "Moreno Valley", label: "Moreno Valley" },
    { value: "Glendale", label: "Glendale" },
    { value: "Huntington Beach", label: "Huntington Beach" },
    { value: "Santa Clarita", label: "Santa Clarita" },
    { value: "Garden Grove", label: "Garden Grove" },
    { value: "Oceanside", label: "Oceanside" },
    { value: "Rancho Cucamonga", label: "Rancho Cucamonga" },
    { value: "Corona", label: "Corona" },
    { value: "Lancaster", label: "Lancaster" },
    { value: "Palmdale", label: "Palmdale" },
    { value: "Salinas", label: "Salinas" },
    { value: "Pomona", label: "Pomona" },
    { value: "Escondido", label: "Escondido" },
    { value: "Torrance", label: "Torrance" },
    { value: "Pasadena", label: "Pasadena" },
    { value: "Sunnyvale", label: "Sunnyvale" },
    { value: "Santa Rosa", label: "Santa Rosa" },
    { value: "Visalia", label: "Visalia" },
    { value: "Concord", label: "Concord" },
    { value: "Thousand Oaks", label: "Thousand Oaks" },
    { value: "Simi Valley", label: "Simi Valley" },
    { value: "Roseville", label: "Roseville" },
    { value: "Victorville", label: "Victorville" },
    { value: "Santa Clara", label: "Santa Clara" },
    { value: "El Monte", label: "El Monte" },
    { value: "Costa Mesa", label: "Costa Mesa" },
    { value: "Inglewood", label: "Inglewood" },
    { value: "West Covina", label: "West Covina" },
    { value: "Murrieta", label: "Murrieta" },
    { value: "Downey", label: "Downey" },
    { value: "Berkeley", label: "Berkeley" },
  ],
  // Add other states with major cities as needed or provide a general list if state not found
};

export const MAJOR_US_CITIES = [
  { value: "NYC", label: "New York City" },
  { value: "LA", label: "Los Angeles" },
  { value: "CHI", label: "Chicago" },
  { value: "HOU", label: "Houston" },
  { value: "PHX", label: "Phoenix" },
  { value: "PHL", label: "Philadelphia" },
  { value: "SA", label: "San Antonio" },
  { value: "SD", label: "San Diego" },
  { value: "DAL", label: "Dallas" },
  { value: "SJ", label: "San Jose" },
];
