// src/constants/icons.ts

export const Icons = {
  addNew: "/Icons/Add New.svg",
  allProducts: "/Icons/All Products.svg",
  arrowRight: "/Icons/Arrow Right.svg",
  cancel: "/Icons/Cancel.svg",
  changePassword: "/Icons/Change Password.svg",
  changePhoto: "/Icons/Change Photo.svg",
  checkmark: "/Icons/Checkmark.svg",
  email: "/Icons/Email.svg",
  emailblue: "/Icons/Emailblue.svg",
  error: "/Icons/Error.svg",
  expand: "/Icons/Expand.svg",
  files: "/Icons/Files.svg",
  hamburgerCompress: "/Icons/Hamburger Compress.svg",
  hide: "/Icons/Hide.svg",
  home: "/Icons/Home.svg",
  logout: "/Icons/Logout.svg",
  notification: "/Icons/Notification.svg",
  notificationblue :"/Icons/Notificationblue.svg",
  organization: "/Icons/Organization.svg",
  pie: "/Icons/Pie.svg",
  production: "/Icons/Production.svg",
  profile: "/Icons/Profile.svg",
  purchase: "/Icons/Purchase.svg",
  sales: "/Icons/Sales.svg",
  search: "/Icons/Search.svg",
  security: "/Icons/Security.svg",
  settings: "/Icons/Settings.svg",
  star: "/Icons/Star.svg",
  transferStock: "/Icons/Trasnfer Stock.svg",
  view: "/Icons/View.svg",
  microsoft: "/Icons/microsoft-logo-svgrepo-com.svg",
  google: "/Icons/GoogleIcon.svg",
  owneruniverse: "/Icons/Owners Universe.svg",
  ownerjungle: "/Icons/Owners Jungle.svg",
  owneranalytics: "/Icons/Owners Analytics.svg",
  ownerinventory: "/Icons/Owners Inventory.svg",
  ownermarketplace: "/Icons/Owners Marketplace.svg",
  owneruniversecoll: "/Icons/Owners Universe coll.svg",
  homewhite: "/Icons/Homewhite.svg",
  organizationwhite: "/Icons/Organizationwhite.svg",
  notificationwhite: "/Icons/Notificationwhite.svg",
  emailwhite: "/Icons/Emailwhite.svg",
  changePasswordwhite: "/Icons/Change Passwordwhite.svg",
  homepageimage: "/Icons/Welcome-cuate.svg",
  OI: "/Icons/OI.svg",

} as const;
